# Generated by Django 5.1.2 on 2024-10-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ["timestamp"]},
        ),
    ]
